# Setup
title:    Prog 1
tagline:  Introduci贸n a la Programaci贸n I
baseurl:  /prog1
zip:	    https://github.com/FacultadDeIngenieria/prog1/zipball/gh-pages

# About/contact
author:
name:       Introduci贸n a la Programaci贸n I
